// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'ru'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	namespace: NamespaceNamespaceTranslation
}

type RootTranslation = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
}

export type NamespaceNamespaceTranslation = {
	/**
	 * THIS IS A PAGE TITLE
	 */
	PAGE_TITLE: string
}

export type Namespaces =
	| 'namespace'

type DisallowNamespaces = {
	/**
	 * reserved for 'namespace'-namespace\
	 * you need to use the `./namespace/index.ts` file instead
	 */
	namespace?: "[typesafe-i18n] reserved for 'namespace'-namespace. You need to use the `./namespace/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	namespace: {
		/**
		 * THIS IS A PAGE TITLE
		 */
		PAGE_TITLE: () => LocalizedString
	}
}

export type Formatters = {}
